### PR TITLE
test(test-all-endpoints):Test All End-points

### PR DESCRIPTION
**Pull request by bzkarim250**
### What does this PR do?
- implement test user signup
- implement test user login
- implement test create blog
- implement test view single blog
- implement test update blog
- implement test delete blog
- implement readme  coverage coverage badge
- implement github CI/CD
### Description of completed task
- adds user signup end-point test
- adds user login end-point test
- adds create blog end-point test
- adds view single blog end-point test
- adds update blog end-point test
- adds delete blog end-point test
- adds github CI/CD Node.js CI
- adds coverage badge and hound to readme using codecov
- adds hound to enforce code quality and style.
### How should this be manually tested?

```
git clone  https://github.com/your-repo.git](https://github.com/bzkarim250/my-brand-bn.git
cd your-project-folder
git checkout test-all-endpoints
npm i
npm run test
npm run coverage
```
### What are the relevant pivotal tracker/Trello/Asana stories?
- Trello [Link](https://trello.com/invite/b/snaWvSIQ/ATTI3f9f62587c3e73feee0d23189e17c79fFF718AF0/my-brand)

### CODE REVIEW

**Comment by bzkarim250** [comment]
[Like Test](https://trello.com/c/uLCWqImP/51-like-test)

**Comment by bzkarim250** [comment]
[Delete Blog Test](https://trello.com/c/KZ9Aub25/53-delete-blog-test)

**Comment by bzkarim250** [comment]
[Comment Test](https://trello.com/c/FPJYNqqM/50-comment-test)

**Comment by bzkarim250** [comment]
[Get Single Blog Test](https://trello.com/c/57RN0hFO/54-get-single-blog-test)

**Comment by bzkarim250** [comment]
[Get Single Blog Test](https://trello.com/c/57RN0hFO/54-get-single-blog-test)

**Comment by bzkarim250** [comment]
[Get Single Blog Test](https://trello.com/c/57RN0hFO/54-get-single-blog-test)

**Review by faid-terence — APPROVED** [review]
Good Work @bzkarim250 !

**Pull request merged**
