### PR TITLE
ft(ft-contact-me):Feature Contact Me

### PR DESCRIPTION
**Pull request by bzkarim250**
### What does this PR do?
- implement send message
- implement retrieve all messages
- implement get single message
- implement delete message
- implement all contact me end-point docs
- implement all contact me end-point tests
### Description of completed task
- adds send new message
- adds retrieve all messages by admin
- adds delete message by admin
- adds view single user by admin
### How should this be manually tested?

```
git clone  https://github.com/bzkarim250/my-brand-bn.git
cd your-project-folder
git ft-contact-me
npm i
npm run dev
npm run test
```
- to access documentation , got to the link [http://localhost:5000/api-docs](http://localhost:5000/api-docs)
- to test end-points , login using swagger docs and pass token where required
### What are the relevant pivotal tracker/Trello/Asana stories?

Trello [Link](https://trello.com/invite/b/snaWvSIQ/ATTI3f9f62587c3e73feee0d23189e17c79fFF718AF0/my-brand)

### CODE REVIEW

**Comment by bzkarim250** [comment]
[Get single message](https://trello.com/c/s7GQTHne/60-get-single-message)

**Comment by bzkarim250** [comment]
[Delete message](https://trello.com/c/iGvNrtXE/61-delete-message)

**Comment by bzkarim250** [comment]
[Get all messages](https://trello.com/c/XgpLb9qd/59-get-all-messages)

**Review by faid-terence — APPROVED** [review]
Nice work @bzkarim250

**Pull request merged**
